---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
matrix:
  include:
  -
    env: CHECK="rubocop"
    stage: static
  -
    env: CHECK='spec' COVERAGE='yes'
    stage: spec
  -
    stage: acceptance
    sudo: required
    env: PLATFORMS=deb_puppet6
    services: docker
    rvm: 2.5.1
    dist: trusty
    before_script:
    - |
      git clone https://github.com/puppetlabs/puppetlabs-motd puppetlabs-motd
      cd puppetlabs-motd
      git reset --hard 88a0015287b943d448271f11b9d6ddc859ba5eca
      printenv
      echo "gem 'puppet_litmus', require: false, git: 'https://github.com/${TRAVIS_PULL_REQUEST_SLUG:-TRAVIS_REPO_SLUG$}', branch: '${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_PULL_REQUEST_BRANCH}'" >> Gemfile
      bundle install --with development --path vendor/bundle --gemfile=./Gemfile
      BUNDLE_GEMFILE=./Gemfile bundle exec rake 'litmus:provision_list[default]'
      BUNDLE_GEMFILE=./Gemfile bundle exec rake 'litmus:install_agent'
      BUNDLE_GEMFILE=./Gemfile bundle exec rake 'litmus:install_module'
    script:
    - BUNDLE_GEMFILE=./Gemfile bundle exec rake litmus:acceptance:parallel